Build for linux falis
variants is no longer a list, but a Variants object.
Setting it to the wrong type caused
  File "/home/cerbero/cerbero/cerbero/cerbero/config.py", line 602, in
cross_compiling
    if self.variants.uwp:
AttributeError: 'list' object has no attribute 'uwp'